### ISSUE TITLE
Ingredients and Cuisine Search fail to display any results, and the tree is not viewable 

### ISSUE THREAD

**Issue by kohaugustine** [levi006/FlavorNet#2]
I just cloned the entire repository and tried running the example locally. At the home page, I have only two boxes, one is for ingredient, the other for cuisine. This is different from the gif that showed the boxes as "Search Ingredient Pairs" and "Searching Ingredients Within a Given Cuisine". 

When I type in the name of any ingredient into the ingredient box, no suggestions would show up in a drag down window; the drag down window does not show up too. When I hit submit, I get a 404 error and a page with the error message "Not Found The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again." The same problem exists with the cuisine search. 

Here I have attached an image showing how the homepage looks like, and you will see what I mean by the homepage appearing different from your Gif image. 

![screenshot from 2017-06-11 12-27-05](https://user-images.githubusercontent.com/6628545/27008393-4cac7076-4ea2-11e7-8ac4-9840dd13b60c.png)

I hope that you can help me with this issue. I think that this project you have done is really nice and it would be a real pity if it does not work on my machine.

The only difference I have done in setting my environment from yours is that I created a conda environment, but only comprising of python 2.7 a few other minimal packages that comes in a conda environment by default. Next I installed all of the packages in requirements.txt using the same command pip install -r requirements.txt and thus had all of your packages installed in this conda environment.

**Comment by dimpyg** [comment]
I am facing the same issue mentioned above. 
What can be done?
Please Help

**Comment by kshkaran2k** [comment]
I have python 2.7 and able to install the app properly. The app url is also working.
When I am trying to search the `Ingredient` or `cuisine`, I am getting an error.

Sharing the screenshot for reference.

Please help me with this.

![flavornet_20180126_190300](https://user-images.githubusercontent.com/9430446/35443915-baed9c74-02d2-11e8-8738-971a0f707ff5.png)
